name: Release
"on":
  push:
    branches:
      - "*.x"
      - main
      - next
      - beta

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PROJECT_FORM_RELEASER_GITHUB_APP_ID }}
          private-key: ${{ secrets.PROJECT_FORM_RELEASER_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
